### ISSUE TITLE
学校增加了码子颜色的选项

### ISSUE THREAD

**Issue by xinkee** [SunHuaiju/zzu_jksb#15]

**Comment by xinkee** [comment]
"myvs_13": "g",
是绿码的选项吗

**Comment by SunHuaiju** [comment]
是的。

**Comment by xinkee** [comment]
.请问是只修改了提交数据吗？我只是把你修改的提交数据变更了下。可是打卡依旧报错，Emmm

**Comment by SunHuaiju** [comment]
您好，感谢您使用该项目。由于我本人已经毕业了，这个项目暂时不维护了，但是我刚才测试了一下应该是没问题的，只需要将submit_data.json文件更新至最新即可。请问您具体报的是什么错？另外如果是您自己测试的话，因为我刚发现学校打卡系统有了更新，在您提交健康信息的时候，会先验证一次当日是否已经提交过信息并是否已经通过审核。每天只能提交一次，若您当天已经提交过您的健康信息的话，使用本项目提交时确实会报错。建议您在明天进行打卡之前测试一下本项目，若能收到正确收到提示邮件，说明项目应该是没问题的。

**Comment by SunHuaiju** [comment]
抱歉这么晚才给您回复，因为今天比较忙。

**Comment by xinkee** [comment]
感谢，我自己测试一下
