### ISSUE TITLE
报错如下，感谢

### ISSUE THREAD

**Issue by xinkee** [SunHuaiju/zzu_jksb#16]
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jksb.v.zzu.edu.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
['https://jksb.v.zzu.edu.cn/vls6sss/zzujksb.dll/first6?ptopid=sFDD22B6BC2264936B096AAB0BF1A7E5D&sid=210825002450373826']/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jksb.v.zzu.edu.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jksb.v.zzu.edu.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jksb.v.zzu.edu.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jksb.v.zzu.edu.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    email_message = post.jksb()
  File "/zzu/jksb.py", line 137, in jksb
    return content.string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by SunHuaiju** [comment]
问题已解决，请再次更新submit_data.json至最新文件即可。

**Comment by xinkee** [comment]
感谢，已测试修复正常
